name: verify

on:
  pull_request:
    branches:
      - main
      - "**"
  push:
    branches:
      - main

permissions:
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: mise run format-check

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: audit licenses, advisories, bans, and sources
        run: mise run deny
      - name: verify publish contents
        run: mise run diet
      - run: mise run lint
      - run: mise run readmes-check
      - run: mise run typos
      - run: mise run package-json-check
      - run: mise run tracey-check

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: ./.github/actions/setup-node
      - name: build
        run: cargo build --release --verbose
      - name: test
        run: mise run test

  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: publish dry-run (bytes2chars only)
        run: mise run publish-dry-run bytes2chars

  test-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: mise run vscode-bin
      - uses: ./.github/actions/setup-node
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
      - run: pnpm --filter jjpwrgem-vscode test
        env:
          DISPLAY: ":99.0"
